name: Build, Push, and Start Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-push-start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DigitalOcean Container Registry
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Build and push Docker image
        env:
          DOCKER_REGISTRY: registry.digitalocean.com/YOUR_REGISTRY_NAME
          IMAGE_NAME: your-image-name
          TAG: latest
        run: |
          echo $DOCKER_REGISTRY
          echo $IMAGE_NAME
          echo $TAG
          docker buildx build --platform linux/amd64 -t $DOCKER_REGISTRY/$IMAGE_NAME:$TAG . --push

      - name: Start Docker container on DigitalOcean Droplet
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          command: compute droplet-action create-container
          args: |
            --droplet-id secrets.DROPLET_ID
            --image $DOCKER_REGISTRY/$IMAGE_NAME:$TAG
            --region FRA1
            --name APP
            --port "8080:8080"
